In [115]:
from sklearn import datasets
from sklearn import svm
import pickle
from sklearn.externals import joblib
import numpy as np
from sklearn import random_projection
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import MultiLabelBinarizer

In [116]:
iris = datasets.load_iris()

In [117]:
digits = datasets.load_digits()

In [118]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [119]:
clf = svm.SVC(gamma=0.001, C=100.)

In [120]:
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [121]:
clf.predict(digits.data[-1:])

array([8])

In [122]:
clf = svm.SVC()

In [123]:
X, y = iris.data, iris.target

In [124]:
clf.fit(X, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [125]:
 s = pickle.dumps(clf)

In [126]:
clf2 = pickle.loads(s)

In [127]:
clf2.predict(X[0:1])

array([0])

In [132]:
y[0]

0

In [86]:
joblib.dump(clf, 'filename.pkl') 

['filename.pkl']

In [87]:
clf = joblib.load('filename.pkl') 

In [88]:
rng = np.random.RandomState(0)

In [89]:
X = rng.rand(10, 2000)

In [90]:
X = np.array(X, dtype='float32')

In [91]:
X.dtype

dtype('float32')

In [92]:
transformer = random_projection.GaussianRandomProjection()

In [93]:
X_new = transformer.fit_transform(X)

In [94]:
X_new.dtype

dtype('float64')

In [95]:
clf = SVC()

In [96]:
clf.fit(iris.data, iris.target)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [97]:
list(clf.predict(iris.data[:3]))

[0, 0, 0]

In [98]:
clf.fit(iris.data, iris.target_names[iris.target])

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [99]:
list(clf.predict(iris.data[:3]))

['setosa', 'setosa', 'setosa']

In [100]:
rng = np.random.RandomState(0)

In [101]:
X = rng.rand(100, 10)

In [102]:
y = rng.binomial(1, 0.5, 100)

In [103]:
X_test = rng.rand(5, 10)

In [104]:
clf = SVC()

In [105]:
clf.set_params(kernel='linear').fit(X, y)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [106]:
clf.predict(X_test)

array([1, 0, 1, 1, 0])

In [107]:
clf.set_params(kernel='rbf').fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [108]:
clf.predict(X_test)

array([0, 0, 0, 1, 0])

In [109]:
X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]
y = [0, 0, 1, 1, 2]

In [110]:
classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X, y).predict(X)

array([0, 0, 1, 1, 2])

In [111]:
y = LabelBinarizer().fit_transform(y)
classif.fit(X, y).predict(X)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [112]:
y = [[0, 1], [0, 2], [1, 3], [0, 2, 3], [2, 4]]
y = MultiLabelBinarizer().fit_transform(y)
classif.fit(X, y).predict(X)

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0]])

In [113]:
####http://scikit-learn.org/stable/tutorial/basic/tutorial.html

In [134]:
from gensim.models.word2vec import Word2Vec

NameError: name 'sentences' is not defined