In [1]:
from sklearn import datasets
from sklearn import svm
import pickle
from sklearn.externals import joblib
import numpy as np
from sklearn import random_projection
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import MultiLabelBinarizer

In [2]:
iris = datasets.load_iris()

In [3]:
digits = datasets.load_digits()

In [4]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
clf = svm.SVC(gamma=0.001, C=100.)

In [6]:
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [7]:
clf.predict(digits.data[-1:])

array([8])

In [8]:
clf = svm.SVC()

In [9]:
X, y = iris.data, iris.target

In [10]:
clf.fit(X, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [11]:
 s = pickle.dumps(clf)

In [12]:
clf2 = pickle.loads(s)

In [13]:
clf2.predict(X[0:1])

array([0])

In [14]:
y[0]

0

In [15]:
joblib.dump(clf, 'filename.pkl') 

['filename.pkl']

In [16]:
clf = joblib.load('filename.pkl') 

In [17]:
rng = np.random.RandomState(0)

In [18]:
X = rng.rand(10, 2000)

In [19]:
X = np.array(X, dtype='float32')

In [20]:
X.dtype

dtype('float32')

In [21]:
transformer = random_projection.GaussianRandomProjection()

In [22]:
X_new = transformer.fit_transform(X)

In [23]:
X_new.dtype

dtype('float64')

In [24]:
clf = SVC()

In [25]:
clf.fit(iris.data, iris.target)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [26]:
list(clf.predict(iris.data[:3]))

[0, 0, 0]

In [27]:
clf.fit(iris.data, iris.target_names[iris.target])

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [28]:
list(clf.predict(iris.data[:3]))

['setosa', 'setosa', 'setosa']

In [29]:
rng = np.random.RandomState(0)

In [30]:
X = rng.rand(100, 10)

In [31]:
y = rng.binomial(1, 0.5, 100)

In [32]:
X_test = rng.rand(5, 10)

In [33]:
clf = SVC()

In [34]:
clf.set_params(kernel='linear').fit(X, y)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [35]:
clf.predict(X_test)

array([1, 0, 1, 1, 0])

In [36]:
clf.set_params(kernel='rbf').fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [37]:
clf.predict(X_test)

array([0, 0, 0, 1, 0])

In [38]:
X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]
y = [0, 0, 1, 1, 2]

In [39]:
classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X, y).predict(X)

array([0, 0, 1, 1, 2])

In [40]:
y = LabelBinarizer().fit_transform(y)
classif.fit(X, y).predict(X)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [41]:
y = [[0, 1], [0, 2], [1, 3], [0, 2, 3], [2, 4]]
y = MultiLabelBinarizer().fit_transform(y)
classif.fit(X, y).predict(X)

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0]])

In [42]:
####http://scikit-learn.org/stable/tutorial/basic/tutorial.html

In [43]:
from gensim.models.word2vec import Word2Vec

In [44]:
model= Word2Vec()

In [45]:
model.build_vocab_from_freq({"Word1": 15, "Word2": 20})

In [46]:
model = Word2Vec(sentences, size=100, window=5, min_count=5, workers=4)

NameError: name 'sentences' is not defined

In [ ]:
#https://radimrehurek.com/gensim/models/word2vec.html